import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { headers } from "next/headers";
import { auth } from "./lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(), 
  });

  const user = session?.user

  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <Header user={user} />
        {children}
      </body>
    </html>
  );
}
