import type React from "react";
import "./globals.css";
import { Suspense } from "react";
import { cookies } from "next/headers";
import { Geist } from "next/font/google";
import type { Metadata } from "next";

import { ThemeProvider } from "@/components/ui/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Header } from "@/features/header/header";
import { Toaster } from "@/components/ui/sonner";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function SidebarWrapper({ children }: { children: React.ReactNode }) {
  "use cache: private";
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <SidebarProvider defaultOpen={defaultOpen}>{children}</SidebarProvider>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geist.className} antialiased min-h-screen bg-black text-foreground `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster position="top-center" richColors />
          <Suspense>
            <SidebarWrapper>
              <div className="w-full flex flex-col">
                <Header />
                {children}
              </div>
            </SidebarWrapper>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
