on:
  push:
    branches: [ dev ]

            
jobs:
  lint:
    name: NextJS Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Lint Check
        run: npm run lint

  build:
    name: NextJS Build
    needs: [lint]
    runs-on: ubuntu-latest
    env:
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      ANALYZE: ${{ secrets.ANALYZE }}

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
